GKE Stateful  Kafka commit
GoogleCloudPlatform/kubernetes-engine-samples pull request #497
Opened 2023-02-16 16:17 UTC by aburhan

Stateful kafka tutorial files

2023-03-06 22:06 UTC, bourgeoisor requested changes
Could you make sure that all the files in this PR are related to the VPA tutorial in one way or another? I flagged a few irrelevant files but there may be some more.

As for the Dockerfile (for the metrics exporter), you'l need 3 things:
- A cloudbuild file (follow this example: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/security/wi-secrets/cloudbuild.yaml)
- The cloudbuild file added to the TF config (follow this example: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/terraform/google-cloud-build-triggers.tf#L194-L207)
- A workflows that builds the container (follow the example here: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/.github/workflows/security-ci.yml)

2023-03-07 15:09 UTC, aburhan commented on gke-vpa-recommendations/scripts/Dockerfile
> +# Copyright 2021 Google LLC
Yes, this is for the hpa metrics exporter

2023-03-07 15:32 UTC, aburhan commented on gke-vpa-recommendations/.gitignore
> +scripts/k8s/metrics-exporter.yaml
removed

2023-03-07 15:32 UTC, aburhan commented on gke-vpa-recommendations/LICENSE
> +
removed

2023-03-07 15:32 UTC, aburhan commented on gke-vpa-recommendations/scripts/CONTRIBUTING.md
> +# How to Contribute
removed

2023-03-07 15:32 UTC, aburhan commented on gke-vpa-recommendations/scripts/LICENSE
> +
removed

2023-03-07 15:33 UTC, aburhan commented
added ci workflow files and removed unnecessary files

2023-03-08 19:08 UTC, bourgeoisor approved these changes

2023-03-08 19:19 UTC, merged