Elastic stack tutorial
GoogleCloudPlatform/kubernetes-engine-samples pull request #824
Opened 2023-08-21 12:39 UTC by TheRealSpaceShip

Tutorial contains:

- DaemonSet hack to increase virtual memory on nodes (for Elasticsearch)
 - CR to create Elasticsearch with ECK operator 
 - CR to create Kibana with ECK operator
 - CR to create Agents in fleet mode with ECK operator
 - Ingress object to setup LB with Google-managed SSL certificate

2023-08-24 21:17 UTC, bourgeoisor requested changes
Just one quick comment--

2023-08-24 21:17 UTC, bourgeoisor commented on elastic-stack/README.md
> +# Elastic Stack on GKE
Would you mind moving this tutorial to either `monitoring/elastic-stack-tutorial/` or `operations/elastic-stack-tutorial/`? I'm trying to get away from single samples as top-level directories, just for clean-up / sustainability purposes

2023-10-13 20:38 UTC, bourgeoisor approved these changes
LGTM.

Let me know when I can merge.

Please also create a follow-up PR once the tutorial is published.

2023-11-09 21:04 UTC, bourgeoisor commented
@TheRealSpaceShip this is still ready to be merged whenever it's ready to go, just let me know

2023-11-10 09:59 UTC, TheRealSpaceShip commented
@bourgeoisor this PR is done and ready to be merged.

2023-11-13 20:55 UTC, bourgeoisor requested changes
Oh, just noticed last-minute
Would you mind moving this from `monitoring/` to `observability/`?
Sorry for any confusion-- I'm in the middle of restructuring samples around :)

2023-11-14 08:24 UTC, TheRealSpaceShip commented
> Oh, just noticed last-minute Would you mind moving this from `monitoring/` to `observability/`? Sorry for any confusion-- I'm in the middle of restructuring samples around :)

No problem. Done.

2023-11-16 22:59 UTC, bourgeoisor approved these changes
LGTM

2023-11-20 20:48 UTC, bourgeoisor commented
@TheRealSpaceShip let me know when this is ready to be merged.

2023-11-21 13:31 UTC, TheRealSpaceShip commented
@bourgeoisor ready to be merged.

2023-11-23 21:50 UTC, merged