Remove unused k8s file
GoogleCloudPlatform/kubernetes-engine-samples pull request #951
Opened 2023-10-11 14:54 UTC by bourgeoisor

Fixes #557 

cc: @shannonxtreme

2023-10-11 15:07 UTC, NimJay requested changes
Thanks for this clean-up.

Should we also remove [`gke-scheduled-autoscaler/k8s/hpa-example.yaml`](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/86241fa0540350eef39bd27f3d61a55f98b74b36/gke-scheduled-autoscaler/k8s/hpa-example.yaml)?

Also, I just noticed that the region tag for the following samples are identical:
* [`/gke-scheduled-autoscaler/k8s/scheduled-autoscaler/hpa-example.yaml`](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/86241fa0540350eef39bd27f3d61a55f98b74b36/gke-scheduled-autoscaler/k8s/scheduled-autoscaler/hpa-example.yaml)
* [`gke-scheduled-autoscaler/k8s/hpa-example.yaml`](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/86241fa0540350eef39bd27f3d61a55f98b74b36/gke-scheduled-autoscaler/k8s/hpa-example.yaml)

2023-10-11 19:26 UTC, bourgeoisor commented
@NimJay no, `hpa-example.yaml` is used here: https://cloud.google.com/kubernetes-engine/docs/tutorials/reducing-costs-by-scaling-down-gke-off-hours#deploy_the_example_application

I also don't want to modify any region tags in this PR since it'd require changing the published tutorial source code as well.

2023-10-12 19:27 UTC, NimJay commented on gke-scheduled-autoscaler/k8s/deployment-example.yaml
Good find! (pointing out that 

Also, it looks like this `deployment-example.yaml` is also used by [that tutorial](https://cloud.google.com/kubernetes-engine/docs/tutorials/reducing-costs-by-scaling-down-gke-off-hours#deploy_the_example_application). 
```
kubectl apply -f ./k8s
```

2023-10-13 16:50 UTC, bourgeoisor commented on gke-scheduled-autoscaler/k8s/deployment-example.yaml
Oh good catch. I had searched for the file name without realizing that command applied everything at once. Seems like we won't be able to simply remove it after all.

2023-10-13 16:59 UTC, closed without merging